import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "./lib/theme/ThemeRegistry";
import { Container, Box } from "@mui/material";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<ThemeRegistry>
					<Box sx={{ display: "flex", minHeight: "100vh" }}>
						<Sidebar />
						<Container maxWidth='xl' sx={{ flex: 1 }}>
							{children}
						</Container>
					</Box>
				</ThemeRegistry>
			</body>
		</html>
	);
}
