import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from "./lib/theme/ThemeRegistry";
import { Container } from "@mui/material";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<ThemeRegistry>
					<Sidebar />
					<Container maxWidth='xl'>{children}</Container>
				</ThemeRegistry>
			</body>
		</html>
	);
}
